# Build stage
FROM node:12.22.0-alpine as build
WORKDIR /app
ENV DISABLE_ESLINT_PLUGIN=true

COPY package*.json ./
RUN npm install --no-package-lock --legacy-peer-deps

COPY . .
RUN npm run build

# Production stage
FROM nginx:1.14.0-alpine

COPY --from=build /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

RUN apk add --no-cache curl openssl

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
